version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/docs-app"
    schedule:
      interval: "monthly"
    groups:
      docs-app-dependencies:
        patterns:
          - "*"
