import { Metadata } from 'next';
import { GoldenScreenshotsGallery } from '@/components/GoldenScreenshotsGallery';
import { getDefaultVersionId } from '@/lib/versions';
import { getCanonicalUrl } from '@/lib/seo';


interface ScreenshotsPageProps {
  params: Promise<{ version: string }>;
}

export async function generateMetadata({ params }: ScreenshotsPageProps): Promise<Metadata> {
  const { version } = await params;

  return {
    title: `Android Screenshots | Charts ${version}`,
    description: 'Screenshots generated by the Charts Android screenshot tests.',
    alternates: {
      canonical: getCanonicalUrl(`/${getDefaultVersionId()}/wiki/screenshots`),
    },
  };
}

export default function ScreenshotsPage() {
  return (
    <article className="mx-auto max-w-[1200px] animate-fade-in">
      <header className="mb-10">
        <h1>Android Screenshots</h1>
        <p className="max-w-[760px]">
          Screenshots generated by the Charts Android screenshot tests. They are loaded directly from the Charts repository.
        </p>
        <a
          href="https://github.com/HDCharts/charts/tree/main/androidApp/src/screenshotTestDebug/reference"
          target="_blank"
          rel="noopener noreferrer"
          className="text-sm text-[var(--link-color)] underline decoration-[0.08em] underline-offset-[0.12em] hover:text-[var(--link-color-hover)]"
        >
          View source screenshots on GitHub
        </a>
      </header>

      <GoldenScreenshotsGallery />
    </article>
  );
}
